/**
 * Freebuff UI Engine — Default Component Registry Seed
 *
 * Pre-seeds the registry with components that ACTUALLY exist in the
 * current project and installed packages. Not metadata about repos
 * that aren't installed — real, importable components.
 */

import type { ComponentEntry } from "./component-registry";

/**
 * Components that exist in this project and can be imported right now.
 * Verified against actual file system and package.json.
 */
export const PROJECT_COMPONENTS: ComponentEntry[] = [
  // === EXISTING OSSZ PROJECT COMPONENTS ===
  {
    name: "button",
    source: "project-local",
    tags: ["interactive", "form", "cta"],
    path: "@/components/ui",
    client: false,
    accessible: true,
    tier: "standard",
    description: "Existing project btn classes in globals.css (btn, btn-primary, btn-secondary, btn-ghost)",
  },
  {
    name: "card",
    source: "project-local",
    tags: ["layout", "container"],
    path: "@/components/ui",
    client: false,
    accessible: true,
    tier: "standard",
    description: "Existing project card class in globals.css",
  },
  {
    name: "input",
    source: "project-local",
    tags: ["form", "interactive"],
    path: "@/components/ui",
    client: false,
    accessible: true,
    tier: "standard",
    description: "Existing project field class in globals.css",
  },
  {
    name: "badge",
    source: "project-local",
    tags: ["status", "label"],
    path: "@/components/ui",
    client: false,
    accessible: true,
    tier: "standard",
    description: "Existing project chip class in globals.css",
  },
  {
    name: "product-card",
    source: "project-local",
    tags: ["product", "grid", "image", "interactive"],
    path: "@/components/product-card",
    client: false,
    accessible: true,
    tier: "standard",
    description: "Product card with image, name, price, quick view, buy now",
  },
  {
    name: "product-grid",
    source: "project-local",
    tags: ["grid", "layout", "product"],
    path: "@/components/product-grid",
    client: false,
    accessible: true,
    tier: "standard",
    description: "Product grid layout for shop/collection pages",
  },
  {
    name: "section-head",
    source: "project-local",
    tags: ["heading", "section", "layout"],
    path: "@/components/ui",
    client: false,
    accessible: true,
    tier: "standard",
    description: "SectionHead with eyebrow, title, intro, and link",
  },
  {
    name: "status-pill",
    source: "project-local",
    tags: ["status", "label", "color"],
    path: "@/components/ui",
    client: false,
    accessible: true,
    tier: "standard",
    description: "StatusPill for order/appointment status display",
  },
  {
    name: "empty-state",
    source: "project-local",
    tags: ["empty", "feedback", "layout"],
    path: "@/components/ui",
    client: false,
    accessible: true,
    tier: "standard",
    description: "EmptyState for empty lists with title, body, action",
  },
  {
    name: "stat",
    source: "project-local",
    tags: ["data", "metric", "layout"],
    path: "@/components/ui",
    client: false,
    accessible: true,
    tier: "standard",
    description: "Stat card with label, value, hint",
  },
  {
    name: "skeleton",
    source: "project-local",
    tags: ["loading", "skeleton", "feedback"],
    path: "@/components/skeletons",
    client: false,
    accessible: true,
    tier: "standard",
    description: "CardGridSkeleton and PageHeaderSkeleton loaders",
  },
  {
    name: "site-header",
    source: "project-local",
    tags: ["navigation", "header", "layout"],
    path: "@/components/site-header",
    client: false,
    accessible: true,
    tier: "standard",
    description: "Server component header with auth, cart, locale",
  },
  {
    name: "site-footer",
    source: "project-local",
    tags: ["navigation", "footer", "layout"],
    path: "@/components/site-footer",
    client: false,
    accessible: true,
    tier: "standard",
    description: "Site footer component",
  },
  {
    name: "concierge",
    source: "project-local",
    tags: ["ai", "chat", "interactive", "client"],
    path: "@/components/concierge",
    client: true,
    accessible: true,
    tier: "standard",
    description: "AI concierge chat widget",
  },

  // === PREMIUM COMPONENTS (shadcn pattern, actually implemented) ===
  {
    name: "button",
    source: "shadcn-ui",
    tags: ["interactive", "form", "cta", "variant"],
    path: "@/components/ui-premium/button",
    client: false,
    accessible: true,
    tier: "premium",
    description: "shadcn-style Button with CVA variants: default, destructive, outline, secondary, ghost, link",
  },
  {
    name: "card",
    source: "shadcn-ui",
    tags: ["layout", "container", "composable"],
    path: "@/components/ui-premium/card",
    client: false,
    accessible: true,
    tier: "premium",
    description: "shadcn-style Card with Header, Content, Footer, Title, Description",
  },
  {
    name: "badge",
    source: "shadcn-ui",
    tags: ["status", "label", "variant"],
    path: "@/components/ui-premium/badge",
    client: false,
    accessible: true,
    tier: "premium",
    description: "shadcn-style Badge with variants: default, secondary, destructive, outline, success, warning",
  },
  {
    name: "input",
    source: "shadcn-ui",
    tags: ["form", "interactive", "text"],
    path: "@/components/ui-premium/input",
    client: false,
    accessible: true,
    tier: "premium",
    description: "shadcn-style Input with focus ring and consistent styling",
  },
  {
    name: "dialog",
    source: "shadcn-ui",
    tags: ["modal", "overlay", "interactive", "client"],
    path: "@/components/ui-premium/dialog",
    client: true,
    accessible: true,
    tier: "premium",
    description: "Radix Dialog with overlay, close button, header/footer. Full keyboard and ARIA support.",
  },
  {
    name: "separator",
    source: "shadcn-ui",
    tags: ["divider", "layout", "horizontal", "vertical"],
    path: "@/components/ui-premium/separator",
    client: false,
    accessible: true,
    tier: "premium",
    description: "Radix Separator for visual dividers",
  },
  {
    name: "label",
    source: "shadcn-ui",
    tags: ["form", "label", "accessibility"],
    path: "@/components/ui-premium/label",
    client: false,
    accessible: true,
    tier: "premium",
    description: "Radix Label for accessible form labels",
  },
  {
    name: "tooltip",
    source: "shadcn-ui",
    tags: ["tooltip", "hover", "info", "client"],
    path: "@/components/ui-premium/tooltip",
    client: true,
    accessible: true,
    tier: "premium",
    description: "Radix Tooltip with Portal, keyboard accessible",
  },
  {
    name: "skeleton",
    source: "shadcn-ui",
    tags: ["loading", "skeleton", "placeholder"],
    path: "@/components/ui-premium/skeleton",
    client: false,
    accessible: true,
    tier: "premium",
    description: "Animated skeleton loader with shimmer effect",
  },

  // === RADIX PRIMITIVES (installed, available) ===
  {
    name: "dropdown-menu",
    source: "radix-ui",
    tags: ["menu", "dropdown", "interactive", "client"],
    path: "@radix-ui/react-dropdown-menu",
    client: true,
    accessible: true,
    tier: "standard",
    description: "Radix DropdownMenu primitive (installed but no wrapper component yet)",
  },
  {
    name: "select",
    source: "radix-ui",
    tags: ["form", "select", "dropdown", "client"],
    path: "@radix-ui/react-select",
    client: true,
    accessible: true,
    tier: "standard",
    description: "Radix Select primitive (installed but no wrapper component yet)",
  },
  {
    name: "tabs",
    source: "radix-ui",
    tags: ["tabs", "navigation", "layout", "client"],
    path: "@radix-ui/react-tabs",
    client: true,
    accessible: true,
    tier: "standard",
    description: "Radix Tabs primitive (installed but no wrapper component yet)",
  },
  {
    name: "switch",
    source: "radix-ui",
    tags: ["toggle", "switch", "form", "client"],
    path: "@radix-ui/react-switch",
    client: true,
    accessible: true,
    tier: "standard",
    description: "Radix Switch primitive (installed but no wrapper component yet)",
  },
];

/**
 * Register all default components into the registry.
 * Call this once at startup or when the engine initializes.
 */
export function registerDefaultComponents(): void {
  // Dynamic import to avoid circular dependencies
  const { registerComponents } = require("./component-registry");
  registerComponents(PROJECT_COMPONENTS);
}
